print("Hexicle is made by Articuno and has help from others if you do wish to help join the Hexicle offical server\n"
      "please if you need code please dont try reprogram it without asking for permissions\n"
      "from Articuno!\n"
      "\n"
      "if you want to suggest something ask on the server too!\n"
      "\n"
      "having issues?\n" 
      "report in the issues page https://github.com/Articuno1234/Hexicle/issues\n"
      "=========================================================================\n"
      "3rd party repos\n"
      "=========================================================================\n"
      "if you want to add an extention/cog to Hexicle give\n"
      "@Articuno™&© | Hexicle Creator#9712 to add it\n" 
      "WARNING! all repos must be in discord.py!\n"
